Add section to explain Sveltos, Flux integration
projectsveltos/sveltos pull request #221
Opened 2024-02-09 13:25 UTC by gianlucam76

With release v0.23.0 Sveltos can seamlessly integrate with Flux to automatically deploy YAML manifests stored in a Git repository.

2024-02-10 08:31 UTC, egrosdou01 reviewed
It might be helpful to point readers to an example of Flux, Sveltos and templating. It can be an all-in-one example. Let me know what you think.

2024-02-10 08:31 UTC, egrosdou01 commented on docs/addons/raw_yaml.md
It might be helpful to point readers to an example of Flux, Sveltos and templating. It can be an all-in-one example. Let me know what you think.

2024-02-10 10:20 UTC, gianlucam76 commented
Thank you. Makes sense. I will try to add such an example. If you have anything in mind, please let me know.

2024-02-10 13:34 UTC, gianlucam76 commented
@egrosdou01 amended adding a template example. Thank you for suggesting it.

2024-02-11 09:51 UTC, egrosdou01 requested changes
We can add the templating section URL for further information and example. Apart from that, looks good to me.

2024-02-11 10:21 UTC, egrosdou01 approved these changes
Looks good! :)

2024-02-11 10:24 UTC, merged